### ISSUE TITLE
[QUESTION] ScrollView prop nestedscrollenabled

### ISSUE THREAD

**Issue by ButuzGOL** [cesardeazevedo/react-native-nested-scroll-view#23]
ScrollView already have prop nestedscrollenabled
https://facebook.github.io/react-native/docs/scrollview#nestedscrollenabled
Does it do the same as you lib ?
I have tried this prop but seems like its not working

**Comment by cesardeazevedo** [comment]
That's interesting, i haven't try the `nestedScrollEnabled ` prop yet, but does this prop make this library obsolete? 😅 

Since this project is a fork from the original ScrollView, it needs a regular rebase, which i failed to do so, i just need some time to rebase make it work with new react-native versions, i hope i can do it this weekend.

**Comment by ButuzGOL** [comment]
pls try for me this prop doesnt work
