### ISSUE TITLE
This app will exhibit the bounce-back scrolling bug

### ISSUE THREAD

**Issue by callmejm** [cesardeazevedo/react-native-nested-scroll-view#6]
Failed to cast mScroller field in ScrollView (probably due to OEM changes to AOSP)! This app will exhibit the bounce-back scrolling bug :(

Suddenly get this error message , any idea ?

**Comment by cesardeazevedo** [comment]
Thanks for reporting,

Can you provide more information?, react-native version and how exactly you are using it, or even a project example that i could reproduce it.

**Comment by kfrozen** [comment]
Hello cesardeazevedo,

I also met this issue when using the NestedScrollView as the scroll component of SectionList. I temporarily fixed it by editing the fling(int velocityY) method in ReactNestedScrollView.java, where I just call super.fling(velocityY) instead of providing custom fling logic.. but according to your comment, the custom fling logic was for supporting adding new content while the ScrollView was animating and thus, I am not sure whether my fix is a proper one or not.. Could you please have a look on this part? 

Thanks.

**Comment by cesardeazevedo** [comment]
@kfrozen Hi, thanks for the information, i'm actually have no idea on how people are using this component, this project is just a fork from the original react-native ScrollView, with a few replacements to work with the native android [nested-scroll-view](https://developer.android.com/reference/android/support/v4/widget/NestedScrollView.html), and i didn't write any custom logic for it.
Can you tell me how exactly you are using it together with SectionList? are you using some CoordinatorLayout? since this component is too generic, i really don't how to get started to look at it, if you could provide a example project that i could take a look, i would really appreciate.

Thanks.

**Comment by kfrozen** [comment]
@cesardeazevedo Hi, thanks for reply. I am using it as a very simple way which just pass the NestedScrollView component to the **renderScrollComponent** props of SectionList, no CoordinatorLayout was used.
 I think your NestedScrollView.js file works good, no need to touch this part. What I changed for testing was the **public void fling(int velocityY)** method inside the java file ReactNestedScrollView.java.

Thanks
